### ISSUE TITLE
HEIGHT value not substituted in genes/<gene>/planaria.js on `pc new machine`

### ISSUE THREAD

**Issue by dymurray** [interplanaria/pc#1]
After doing `pc new machine` and filling out the prompts I see an error when trying to run `pc start` due to the fact that planaria.js has:
```
planaria: '0.0.1',
from: HEIGHT,
...
```

The error isn't obvious to the end user unless you capture the logs of the container fast enough:
```
####################                          
Reading /app/genes/1HYUCuTsi3W28cHga2ZnVuf38frMo2DPGa
/app/genes/1HYUCuTsi3W28cHga2ZnVuf38frMo2DPGa/planaria.js:8
  from: HEIGHT,                                                                          
        ^                                                                            
                                                       
ReferenceError: HEIGHT is not defined          
    at Object.<anonymous> (/app/genes/1HYUCuTsi3W28cHga2ZnVuf38frMo2DPGa/planaria.js:8:9)
    at Module._compile (module.js:653:30)                
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)     
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)           
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)                                        
    at /app/index.js:44:15                            
    at Array.forEach (<anonymous>)   
```

**Comment by unwriter** [comment]
Should be resolved with this https://github.com/interplanaria/pc/commit/ca15660beb3453ee6d27813bdd9d626e752f83ab

Please try

```
npm install -g planaria
```

again to install the latest version `0.0.43` and confirm if it fixes the problem.

**Comment by dymurray** [comment]
Thanks @unwriter. That works.
